import { useGetAnalyticsOverview } from '@workspace/api-client';
import { LoadingSkeleton } from '@/components/shared/loading-skeleton';
import { ErrorState } from '@/components/shared/error-state';
import { Panel } from '@/components/shared/panel';
import { PageTitle } from '@/components/shared/page-title';
import { ORG_SLUG } from '@/lib/constants';
import { formatCurrency } from '@/lib/format';

export default function Analytics() {
  const query = useGetAnalyticsOverview(ORG_SLUG); if (query.isLoading) return <><PageTitle title="Analytics" /><LoadingSkeleton rows={5} /></>; if (query.isError || !query.data) return <ErrorState retry={() => query.refetch()} />; const d = query.data;
  return <><PageTitle eyebrow="Finance leadership" title="The shape of spend." description="A clear read on where control is working — and where it is being bypassed." /><div className="analytics-grid"><Panel className="wide-chart"><div className="card-heading"><div><p className="eyebrow">Spend by category</p><h2>Where money is moving</h2></div></div><div className="bar-chart">{d.spendByCategory.map((item) => <div className="chart-bar" key={item.label} data-testid={`chart-category-${item.label}`}><span style={{ height: `${Math.max(12, (item.amountCents / Math.max(...d.spendByCategory.map((x) => x.amountCents))) * 100)}%` }} /><small>{item.label}</small><b>{formatCurrency(item.amountCents)}</b></div>)}</div></Panel><Panel><p className="eyebrow">Approval SLA</p><h2>{d.approvalSla.averageDays.toFixed(1)} days</h2><p className="body-copy">Average decision time against a {d.approvalSla.targetDays}-day target.</p><div className="big-stat-good">{d.approvalSla.onTimePct.toFixed(1)}% <small>on time</small></div></Panel><Panel><p className="eyebrow">Maverick spend</p><h2>{formatCurrency(d.maverickSpend.amountCents)}</h2><p className="body-copy">Spend outside the approved path.</p><div className="maverick-track"><span style={{ width: `${d.maverickSpend.pctOfSpend}%` }} /></div><small>{d.maverickSpend.pctOfSpend.toFixed(1)}% of total spend</small></Panel><Panel className="wide-chart"><div className="card-heading"><div><p className="eyebrow">Budget versus actual</p><h2>Plan and reality</h2></div></div><div className="budget-chart">{d.budgetVsActual.map((item) => <div key={item.label} data-testid={`chart-budget-${item.label}`}><span>{item.label}</span><div><i style={{ width: `${Math.min(100, item.spentCents / item.allocatedCents * 100)}%` }} /><em>{formatCurrency(item.spentCents)} / {formatCurrency(item.allocatedCents)}</em></div></div>)}</div></Panel></div></>;
}
