import { useState } from 'react';
import { ArrowLeft, FileCheck2, RefreshCw } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { useListInvoices, useResolveInvoiceException, useRunInvoiceMatch } from '@workspace/api-client';
import { StatusBadge } from '@/components/shared/status-badge';
import { ActionButton } from '@/components/shared/action-button';
import { Panel } from '@/components/shared/panel';
import { PageTitle } from '@/components/shared/page-title';
import { ORG_SLUG } from '@/lib/constants';
import { formatCurrency } from '@/lib/format';

export default function InvoiceMatch() {
  const { id = '' } = useParams<{ id: string }>(); const invoices = useListInvoices(ORG_SLUG, {}); const run = useRunInvoiceMatch(); const resolve = useResolveInvoiceException(); const [match, setMatch] = useState<any>(null); const invoice = invoices.data?.find((item) => item.id === id);
  return <><Link href="/app/ledgerway/invoices" className="back-link" data-testid="link-back-invoices"><ArrowLeft size={15} /> Invoices</Link><PageTitle eyebrow="Three-way control" title={invoice ? invoice.invoiceNumber : 'Invoice match'} description={invoice ? `${invoice.vendorName} · ${formatCurrency(invoice.totalAmountCents)}` : 'Compare invoice, PO, and receipt evidence.'} action={<StatusBadge value={match?.status || invoice?.matchStatus} />} /><Panel className="match-card">{!match ? <div className="match-empty"><span className="match-symbol"><FileCheck2 size={28} /></span><h2>Run the match when evidence is ready.</h2><p>Ledgerway will compare every invoice line against the purchase order and receiving record.</p><ActionButton className="button-primary" onClick={() => run.mutate({ orgSlug: ORG_SLUG, invoiceId: id }, { onSuccess: setMatch })} disabled={run.isPending} data-testid="button-run-match"><RefreshCw size={15} /> {run.isPending ? 'Comparing evidence…' : 'Run three-way match'}</ActionButton></div> : <><div className="match-result-head"><div><p className="eyebrow">Match result</p><h2>{match.summary}</h2></div><StatusBadge value={match.status} /></div><div className="data-table-wrap"><table><thead><tr><th>Line</th><th>Invoice qty</th><th>PO qty</th><th>Received qty</th><th>Status</th></tr></thead><tbody>{match.lines.map((line: any, i: number) => <tr key={i} data-testid={`row-match-line-${i}`}><td className="table-primary">{line.description}</td><td>{line.invoiceQuantity}</td><td>{line.poQuantity}</td><td>{line.receivedQuantity}</td><td><StatusBadge value={line.status} /></td></tr>)}</tbody></table></div>{match.status === 'exception' && <div className="exception-actions"><ActionButton className="button-primary" onClick={() => resolve.mutate({ orgSlug: ORG_SLUG, invoiceId: id, data: { resolution: 'approve', note: 'Reviewed in Ledgerway match workspace.' } })} data-testid="button-approve-exception">Approve exception</ActionButton><ActionButton className="button-secondary" onClick={() => resolve.mutate({ orgSlug: ORG_SLUG, invoiceId: id, data: { resolution: 'request_correction', note: 'Please correct the invoice and resubmit.' } })} data-testid="button-request-correction">Request correction</ActionButton></div>}</>}</Panel></>;
}
